### ISSUE TITLE
It asks for update every time I load anki

### ISSUE THREAD

**Issue by yetihk** [mankinence/ImageResizer#23] opened 2021-06-05 01:04 UTC
Every time I load Anki it asks me to upload this add on:
https://i.imgur.com/IWiJ1oD.png

How do I stop that?

Windows 10
Version ⁨2.1.44 (b2b3275f)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

I only have one other add on installed (Image Occlusion)

**Comment by searene** [comment] 2021-06-05 01:50
You can try this:

1. Delete ImageResizer: Click on Tools -> Add-ons -> Select ImageResizer -> Delete
2. Install ImageResizer again.

**Comment by searene** [comment] 2021-06-05 01:51
This could be a bug in a previous version, so you can try if it could be solved by reinstalling it in this way.

**Comment by ghost** [comment] 2021-07-04 13:29
I confirm – reinstalling resolves the issue.

**Comment by tboomer** [comment] 2022-03-23 13:33
I have had the same problem for at least the last two updates to the add-on. Both times I have used the work-around described in this thread successfully, but it's a nuisance. Please fix the problem at the source in the next update so it does not recur.

**Comment by searene** [comment] 2022-03-24 06:36
@tboomer That's strange, I thought it was due to SSL being disabled in the past, I fixed it about a year ago. So if you update it again this time, the problem should disappear. But that doesn't seem to be the case.

I cannot reproduce this problem by myself, that's why it‘s hard to pinpoint the reason and fix it.

**Comment by tboomer** [comment] 2022-03-24 09:39
Thank you for your response. I appreciate your predicament. I'd be willing to install the previous version from a file and go through the Anki update process again if that would be useful. I am running Anki 2.1.49 on Windows 10. Let me know if I can be helpful. I like the add-on a lot.

**Comment by searene** [comment] 2022-03-24 14:15
> Thank you for your response. I appreciate your predicament. I'd be willing to install the previous version from a file and go through the Anki update process again if that would be useful. I am running Anki 2.1.49 on Windows 10. Let me know if I can be helpful. I like the add-on a lot.

Thanks for your help! I want to get some information about your ImageResizer's version configuration, to obtain this, you need to take the following steps:

1. Open Anki, click on Tools -> Add-ons to open the add-on dialog.
2. Choose `ImageResizer`, click on the `View Files` button.
3. You will see a file called `meta.json` in the add-on folder, please open it, copy and paste its contents here.

This file only contains some information about the addon, it contains nothing about your personal data, here is the description about all the fields in the file, I got it from the Anki source code:

```python
{
    # the name of the folder
    "package": {"type": "string", "minLength": 1, "meta": False},
    # the displayed name to the user
    "name": {"type": "string", "meta": True},
    # the time the add-on was last modified
    "mod": {"type": "number", "meta": True},
    # a list of other packages that conflict
    "conflicts": {"type": "array", "items": {"type": "string"}, "meta": True},
    # the minimum 2.1.x version this add-on supports
    "min_point_version": {"type": "number", "meta": True},
    # if negative, abs(n) is the maximum 2.1.x version this add-on supports
    # if positive, indicates version tested on, and is ignored
    "max_point_version": {"type": "number", "meta": True},
    # AnkiWeb sends this to indicate which branch the user downloaded.
    "branch_index": {"type": "number", "meta": True},
    # version string set by the add-on creator
    "human_version": {"type": "string", "meta": True},
}
```

Anki compares the version set in this file to the version stored in its remote database (https://ankiweb.net/shared/updates/1214357311?v=3), It asks for updates when the local version is less than the remote version. So the contents of the your file may give me some clue to the problem.

**Comment by tboomer** [comment] 2022-03-24 15:34
Here are the contents of the file:
{"name": "ImageResizer", "mod": 1647738668, "min_point_version": 0, "max_point_version": 50, "branch_index": 0}

Let me know if you need anything else.

**Comment by searene** [comment] 2022-03-25 09:54
@tboomer Thanks, the contents of the file are totally normal. Could you try the following steps?

1. Modify the value of `mod` from `1647738668` to `1618105426`, then save the file.
2. Restart anki, wait for Anki to prompt you to update the add-on. If it doesn't, click on `Tools` -> `Add-ons` -> `Check for Updates` to manually start the checking process.
3. After Anki prompts you to update the addon, update it. Then check if Anki keeps prompting you for updating, just as the bug mentioned above.

P.S. A little explanation: The value of `mod` denotes the last time the add-on is updated. By changing it to a smaller value, Anki would think that the add-on should be updated, thus triggering the updating process.

**Comment by tboomer** [comment] 2022-03-25 10:31
I performed these steps and after saying "Yes" to update the add-on, Anki still says an update is needed when I check again. I tried closing and restarting Anki and still got the same result. If it's relevant, the value in the json file after doing this is still 1618105426.

**Comment by searene** [comment] 2022-03-26 02:54
@tboomer Thanks, that's very helpful. This bug only seems to occur on Windows. The reason is that Anki tries to move the log file that ImageResizer uses while updating, but Anki fails because Windows doesn't allow to move a file that is being used, thus the update fails. That's why Anki always prompts an update because none of the previous updates is successful.

Seeing that the log isn't that helpful in those years, I'll remove the logging functionalities in ImageResizer. However since Anki still tries to move the logging files in the old version, the next update will still fail, and the user still needs to repeat the above steps to finish the update. After updating to the next version successfully, the bug will not occur anymore.

I'll roll out a new version these days.

**Comment by searene** [comment] 2022-03-26 03:21
I've uploaded the new version to Anki.

**Comment by tboomer** [comment] 2022-03-26 10:21
Thank you! I've reinstalled the new version.

**Closed as completed** 2022-03-26 12:32 UTC

**Comment by spherocyte100** [comment] 2022-11-08 16:59
Thanks this was very helpful. Had the same issue.
Resolved
